/**
 * Demo listings.
 *
 * Used only when the API is unreachable (NEXT_PUBLIC_API_URL unset, backend
 * not running, or a preview deploy before the backend exists). This keeps the
 * site presentable for design reviews and for a first Vercel deploy.
 *
 * Nothing imports this array directly except lib/api.ts — components always go
 * through getListings() / getListingById(), so swapping the data source never
 * touches a component.
 */

import type { Listing } from './types';

/** ISO timestamp for N days ago, so "Bugun joylandi" badges always demo well. */
function daysAgo(days: number, hour = 9): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

/** Date-only string (YYYY-MM-DD) N days ago — used for harvest dates. */
function harvest(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().slice(0, 10);
}

export const mockListings: Listing[] = [
  {
    id: 'demo-1',
    productName: 'Yangi pomidor',
    category: 'vegetables',
    price: 8000,
    quantity: '500 kg',
    village: 'Chorbog’',
    district: 'urgut',
    districtLabel: 'Urgut',
    region: 'samarkand',
    harvestDate: harvest(0),
    phone: '+998901234567',
    telegramUsername: 'dehqon_ali',
    whatsappNumber: '+998901234567',
    isSoldOut: false,
    createdAt: daysAgo(0, 7),
    description: 'Bugun ertalab uzilgan, issiqxona pomidori. Yashiklarda tayyor.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 34,
    seller: {
      id: 'demo-s1',
      fullName: 'Ali Rahimov',
      phone: '+998901234567',
      telegramUsername: 'dehqon_ali',
      village: 'Chorbog’',
      district: 'Urgut',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-2',
    productName: 'Qora uzum (Husayni)',
    category: 'fruits',
    price: 15000,
    quantity: '300 kg',
    village: 'Bulung’ur',
    district: 'bulungur',
    districtLabel: 'Bulung’ur',
    region: 'samarkand',
    harvestDate: harvest(1),
    phone: '+998935556677',
    telegramUsername: 'uzum_bogi',
    isSoldOut: false,
    createdAt: daysAgo(0, 11),
    description: 'O’z bog’imizdan. Kamida 50 kg dan olinadi.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 87,
    seller: {
      id: 'demo-s2',
      fullName: 'Shuhrat Nazarov',
      phone: '+998935556677',
      telegramUsername: 'uzum_bogi',
      village: 'Bulung’ur',
      district: 'Bulung’ur',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-3',
    productName: 'Bug’doy (oq)',
    category: 'grains',
    price: 4500,
    quantity: '2000 kg',
    village: 'Qo’shrabot',
    district: 'qoshrabot',
    districtLabel: 'Qo’shrabot',
    region: 'samarkand',
    harvestDate: harvest(21),
    phone: '+998915554433',
    isSoldOut: false,
    createdAt: daysAgo(0, 14),
    description: 'Quritilgan, tozalangan. Qoplarda, 50 kg dan.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 12,
    seller: {
      id: 'demo-s3',
      fullName: 'Bahodir Ergashev',
      phone: '+998915554433',
      village: 'Qo’shrabot',
      district: 'Qo’shrabot',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-4',
    productName: 'Qatiq (uy sharoitida)',
    category: 'dairy',
    price: 12000,
    quantity: '40 litr',
    village: 'Jomboy',
    district: 'jomboy',
    districtLabel: 'Jomboy',
    region: 'samarkand',
    harvestDate: harvest(0),
    phone: '+998977778899',
    whatsappNumber: '+998977778899',
    isSoldOut: false,
    createdAt: daysAgo(1, 8),
    description: 'Har kuni ertalab tayyorlanadi. Idish o’zingizdan.',
    unit: 'liter',
    unitLabel: 'litr',
    views: 51,
    seller: {
      id: 'demo-s4',
      fullName: 'Nodira opa',
      phone: '+998977778899',
      village: 'Jomboy',
      district: 'Jomboy',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-5',
    productName: 'Yong’oq (mag’zi)',
    category: 'dried',
    price: 75000,
    quantity: '120 kg',
    village: 'Payariq',
    district: 'payariq',
    districtLabel: 'Payariq',
    region: 'samarkand',
    harvestDate: harvest(30),
    phone: '+998907776655',
    telegramUsername: 'yongoq_savdo',
    whatsappNumber: '+998907776655',
    isSoldOut: false,
    createdAt: daysAgo(1, 16),
    description: 'Yaxshi quritilgan, oq mag’iz. Namuna yuboriladi.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 143,
    seller: {
      id: 'demo-s5',
      fullName: 'Farrux Qodirov',
      phone: '+998907776655',
      telegramUsername: 'yongoq_savdo',
      village: 'Payariq',
      district: 'Payariq',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-6',
    productName: 'Bodring',
    category: 'vegetables',
    price: 6500,
    quantity: '800 kg',
    village: 'Ishtixon',
    district: 'ishtixon',
    districtLabel: 'Ishtixon',
    region: 'samarkand',
    harvestDate: harvest(1),
    phone: '+998933332211',
    telegramUsername: 'issiqxona_uz',
    isSoldOut: false,
    createdAt: daysAgo(2, 10),
    description: 'Issiqxonadan, har kuni yangi partiya.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 66,
    seller: {
      id: 'demo-s6',
      fullName: 'Sardor Tursunov',
      phone: '+998933332211',
      telegramUsername: 'issiqxona_uz',
      village: 'Ishtixon',
      district: 'Ishtixon',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-7',
    productName: 'O’rik (quritilgan)',
    category: 'fruits',
    price: 32000,
    quantity: '250 kg',
    village: 'Nurobod',
    district: 'nurobod',
    districtLabel: 'Nurobod',
    region: 'samarkand',
    harvestDate: harvest(45),
    phone: '+998944445566',
    telegramUsername: 'quruq_meva',
    isSoldOut: false,
    createdAt: daysAgo(3, 9),
    description: 'Oltingugurtsiz quritilgan. Ulgurji narx kelishiladi.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 98,
    seller: {
      id: 'demo-s7',
      fullName: 'Zulfiya Karimova',
      phone: '+998944445566',
      telegramUsername: 'quruq_meva',
      village: 'Nurobod',
      district: 'Nurobod',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-8',
    productName: 'Kartoshka',
    category: 'vegetables',
    price: 5000,
    quantity: '1500 kg',
    village: 'G’allaorol',
    district: 'gallaorol',
    districtLabel: 'G’allaorol',
    region: 'jizzakh',
    harvestDate: harvest(14),
    phone: '+998996667788',
    isSoldOut: false,
    createdAt: daysAgo(4, 13),
    description: 'Yirik, saralangan. Yuk mashinasiga yuklab beramiz.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 40,
    seller: {
      id: 'demo-s8',
      fullName: 'Jamshid Sobirov',
      phone: '+998996667788',
      village: 'G’allaorol',
      district: 'G’allaorol',
      region: 'jizzakh',
    },
  },
  {
    id: 'demo-9',
    productName: 'Asal (tog’ asali)',
    category: 'honey',
    price: 90000,
    quantity: '60 litr',
    village: 'Zomin',
    district: 'zomin',
    districtLabel: 'Zomin',
    region: 'jizzakh',
    harvestDate: harvest(20),
    phone: '+998911112233',
    telegramUsername: 'tog_asali',
    whatsappNumber: '+998911112233',
    isSoldOut: false,
    createdAt: daysAgo(5, 12),
    description: 'O’z asalarixonamizdan. Tatib ko’rish mumkin.',
    unit: 'liter',
    unitLabel: 'litr',
    views: 210,
    seller: {
      id: 'demo-s9',
      fullName: 'Otabek Yo’ldoshev',
      phone: '+998911112233',
      telegramUsername: 'tog_asali',
      village: 'Zomin',
      district: 'Zomin',
      region: 'jizzakh',
    },
  },
  {
    id: 'demo-10',
    productName: 'Anor',
    category: 'fruits',
    price: 18000,
    quantity: '400 kg',
    village: 'Qumqo’rg’on',
    district: 'qumqorgon',
    districtLabel: 'Qumqo’rg’on',
    region: 'surkhandarya',
    harvestDate: harvest(7),
    phone: '+998902223344',
    telegramUsername: 'anor_surxon',
    isSoldOut: false,
    createdAt: daysAgo(6, 15),
    description: 'Shirin nav, yirik. Yashiklarda.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 77,
    seller: {
      id: 'demo-s10',
      fullName: 'Ulug’bek Xolmatov',
      phone: '+998902223344',
      telegramUsername: 'anor_surxon',
      village: 'Qumqo’rg’on',
      district: 'Qumqo’rg’on',
      region: 'surkhandarya',
    },
  },
  {
    id: 'demo-11',
    productName: 'Sarimsoq',
    category: 'vegetables',
    price: 22000,
    quantity: '180 kg',
    village: 'Kitob',
    district: 'kitob',
    districtLabel: 'Kitob',
    region: 'kashkadarya',
    harvestDate: harvest(25),
    phone: '+998939998877',
    isSoldOut: true,
    createdAt: daysAgo(8, 11),
    description: 'Quritilgan, o’ralgan. Hozircha tugagan.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 55,
    seller: {
      id: 'demo-s11',
      fullName: 'Rustam Nazarov',
      phone: '+998939998877',
      village: 'Kitob',
      district: 'Kitob',
      region: 'kashkadarya',
    },
  },
  {
    id: 'demo-12',
    productName: 'Sut (sigir suti)',
    category: 'dairy',
    price: 7000,
    quantity: '100 litr',
    village: 'Oqdaryo',
    district: 'oqdaryo',
    districtLabel: 'Oqdaryo',
    region: 'samarkand',
    harvestDate: harvest(0),
    phone: '+998905556644',
    whatsappNumber: '+998905556644',
    isSoldOut: false,
    createdAt: daysAgo(9, 7),
    description: 'Har kuni ertalab va kechqurun sog’iladi.',
    unit: 'liter',
    unitLabel: 'litr',
    views: 29,
    seller: {
      id: 'demo-s12',
      fullName: 'Dilshod Ochilov',
      phone: '+998905556644',
      village: 'Oqdaryo',
      district: 'Oqdaryo',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-13',
    productName: 'Qovun (Mirzachul)',
    category: 'melons',
    price: 6000,
    quantity: '3 tonna',
    village: 'Mirzacho’l',
    district: 'mirzachol',
    districtLabel: 'Mirzacho’l',
    region: 'jizzakh',
    harvestDate: harvest(2),
    phone: '+998945551122',
    telegramUsername: 'qovun_mirzachul',
    isSoldOut: false,
    createdAt: daysAgo(1, 16),
    description: 'Shirin, yirik qovunlar. Ulgurji xaridorga chegirma bor.',
    unit: 'kg',
    unitLabel: 'kg',
    views: 41,
    seller: {
      id: 'demo-s13',
      fullName: 'Shavkat Ergashev',
      phone: '+998945551122',
      telegramUsername: 'qovun_mirzachul',
      village: 'Mirzacho’l',
      region: 'jizzakh',
    },
  },
  {
    id: 'demo-14',
    productName: 'Ko’k piyoz va shivit',
    category: 'greens',
    price: 2000,
    quantity: '200 bog’',
    village: 'Toyloq',
    district: 'toyloq',
    districtLabel: 'Toyloq',
    region: 'samarkand',
    harvestDate: harvest(0),
    phone: '+998917776655',
    isSoldOut: false,
    createdAt: daysAgo(0, 6),
    description: 'Har kuni ertalab yangi uziladi.',
    unit: 'bunch',
    unitLabel: 'bog’',
    views: 12,
    seller: {
      id: 'demo-s14',
      fullName: 'Nodira Qodirova',
      phone: '+998917776655',
      village: 'Toyloq',
      region: 'samarkand',
    },
  },
];

export function getMockListingById(id: string): Listing | undefined {
  return mockListings.find((l) => l.id === id);
}
