/**
 * Demo listings.
 *
 * Used only when the API is unreachable (NEXT_PUBLIC_API_URL unset, backend
 * not running, or a preview deploy before the backend exists). This keeps the
 * site presentable for design reviews and for a first Vercel deploy.
 *
 * Nothing imports this array directly except lib/api.ts — components always go
 * through getListings() / getListingById(), so swapping the data source never
 * touches a component.
 */

import type { Listing } from './types';

/** ISO timestamp for N days ago, so "Bugun joylandi" badges always demo well. */
function daysAgo(days: number, hour = 9): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

/** Date-only string (YYYY-MM-DD) N days ago — used for harvest dates. */
function harvest(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().slice(0, 10);
}

export const mockListings: Listing[] = [
  {
    id: 'demo-1',
    productName: 'Yangi pomidor',
    category: 'sabzavotlar',
    pricePerKg: 8000,
    quantityKg: 500,
    village: 'Chorbog’',
    district: 'Urgut',
    region: 'samarkand',
    harvestDate: harvest(0),
    phone: '+998901234567',
    telegramUsername: 'dehqon_ali',
    whatsappNumber: '+998901234567',
    isSoldOut: false,
    createdAt: daysAgo(0, 7),
    description: 'Bugun ertalab uzilgan, issiqxona pomidori. Yashiklarda tayyor.',
    unitLabel: 'kg',
    views: 34,
    seller: {
      id: 'demo-s1',
      fullName: 'Ali Rahimov',
      phone: '+998901234567',
      telegramUsername: 'dehqon_ali',
      village: 'Chorbog’',
      district: 'Urgut',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-2',
    productName: 'Qora uzum (Husayni)',
    category: 'mevalar',
    pricePerKg: 15000,
    quantityKg: 300,
    village: 'Bulung’ur',
    district: 'Bulung’ur',
    region: 'samarkand',
    harvestDate: harvest(1),
    phone: '+998935556677',
    telegramUsername: 'uzum_bogi',
    isSoldOut: false,
    createdAt: daysAgo(0, 11),
    description: 'O’z bog’imizdan. Kamida 50 kg dan olinadi.',
    unitLabel: 'kg',
    views: 87,
    seller: {
      id: 'demo-s2',
      fullName: 'Shuhrat Nazarov',
      phone: '+998935556677',
      telegramUsername: 'uzum_bogi',
      village: 'Bulung’ur',
      district: 'Bulung’ur',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-3',
    productName: 'Bug’doy (oq)',
    category: 'don',
    pricePerKg: 4500,
    quantityKg: 2000,
    village: 'Qo’shrabot',
    district: 'Qo’shrabot',
    region: 'samarkand',
    harvestDate: harvest(21),
    phone: '+998915554433',
    isSoldOut: false,
    createdAt: daysAgo(0, 14),
    description: 'Quritilgan, tozalangan. Qoplarda, 50 kg dan.',
    unitLabel: 'kg',
    views: 12,
    seller: {
      id: 'demo-s3',
      fullName: 'Bahodir Ergashev',
      phone: '+998915554433',
      village: 'Qo’shrabot',
      district: 'Qo’shrabot',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-4',
    productName: 'Qatiq (uy sharoitida)',
    category: 'sut_mahsulotlari',
    pricePerKg: 12000,
    quantityKg: 40,
    village: 'Jomboy',
    district: 'Jomboy',
    region: 'samarkand',
    harvestDate: harvest(0),
    phone: '+998977778899',
    whatsappNumber: '+998977778899',
    isSoldOut: false,
    createdAt: daysAgo(1, 8),
    description: 'Har kuni ertalab tayyorlanadi. Idish o’zingizdan.',
    unitLabel: 'litr',
    views: 51,
    seller: {
      id: 'demo-s4',
      fullName: 'Nodira opa',
      phone: '+998977778899',
      village: 'Jomboy',
      district: 'Jomboy',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-5',
    productName: 'Yong’oq (mag’zi)',
    category: 'yongoqlar',
    pricePerKg: 75000,
    quantityKg: 120,
    village: 'Payariq',
    district: 'Payariq',
    region: 'samarkand',
    harvestDate: harvest(30),
    phone: '+998907776655',
    telegramUsername: 'yongoq_savdo',
    whatsappNumber: '+998907776655',
    isSoldOut: false,
    createdAt: daysAgo(1, 16),
    description: 'Yaxshi quritilgan, oq mag’iz. Namuna yuboriladi.',
    unitLabel: 'kg',
    views: 143,
    seller: {
      id: 'demo-s5',
      fullName: 'Farrux Qodirov',
      phone: '+998907776655',
      telegramUsername: 'yongoq_savdo',
      village: 'Payariq',
      district: 'Payariq',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-6',
    productName: 'Bodring',
    category: 'sabzavotlar',
    pricePerKg: 6500,
    quantityKg: 800,
    village: 'Ishtixon',
    district: 'Ishtixon',
    region: 'samarkand',
    harvestDate: harvest(1),
    phone: '+998933332211',
    telegramUsername: 'issiqxona_uz',
    isSoldOut: false,
    createdAt: daysAgo(2, 10),
    description: 'Issiqxonadan, har kuni yangi partiya.',
    unitLabel: 'kg',
    views: 66,
    seller: {
      id: 'demo-s6',
      fullName: 'Sardor Tursunov',
      phone: '+998933332211',
      telegramUsername: 'issiqxona_uz',
      village: 'Ishtixon',
      district: 'Ishtixon',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-7',
    productName: 'O’rik (quritilgan)',
    category: 'mevalar',
    pricePerKg: 32000,
    quantityKg: 250,
    village: 'Nurobod',
    district: 'Nurobod',
    region: 'samarkand',
    harvestDate: harvest(45),
    phone: '+998944445566',
    telegramUsername: 'quruq_meva',
    isSoldOut: false,
    createdAt: daysAgo(3, 9),
    description: 'Oltingugurtsiz quritilgan. Ulgurji narx kelishiladi.',
    unitLabel: 'kg',
    views: 98,
    seller: {
      id: 'demo-s7',
      fullName: 'Zulfiya Karimova',
      phone: '+998944445566',
      telegramUsername: 'quruq_meva',
      village: 'Nurobod',
      district: 'Nurobod',
      region: 'samarkand',
    },
  },
  {
    id: 'demo-8',
    productName: 'Kartoshka',
    category: 'sabzavotlar',
    pricePerKg: 5000,
    quantityKg: 1500,
    village: 'G’allaorol',
    district: 'G’allaorol',
    region: 'jizzakh',
    harvestDate: harvest(14),
    phone: '+998996667788',
    isSoldOut: false,
    createdAt: daysAgo(4, 13),
    description: 'Yirik, saralangan. Yuk mashinasiga yuklab beramiz.',
    unitLabel: 'kg',
    views: 40,
    seller: {
      id: 'demo-s8',
      fullName: 'Jamshid Sobirov',
      phone: '+998996667788',
      village: 'G’allaorol',
      district: 'G’allaorol',
      region: 'jizzakh',
    },
  },
  {
    id: 'demo-9',
    productName: 'Asal (tog’ asali)',
    category: 'boshqa',
    pricePerKg: 90000,
    quantityKg: 60,
    village: 'Zomin',
    district: 'Zomin',
    region: 'jizzakh',
    harvestDate: harvest(20),
    phone: '+998911112233',
    telegramUsername: 'tog_asali',
    whatsappNumber: '+998911112233',
    isSoldOut: false,
    createdAt: daysAgo(5, 12),
    description: 'O’z asalarixonamizdan. Tatib ko’rish mumkin.',
    unitLabel: 'litr',
    views: 210,
    seller: {
      id: 'demo-s9',
      fullName: 'Otabek Yo’ldoshev',
      phone: '+998911112233',
      telegramUsername: 'tog_asali',
      village: 'Zomin',
      district: 'Zomin',
      region: 'jizzakh',
    },
  },
  {
    id: 'demo-10',
    productName: 'Anor',
    category: 'mevalar',
    pricePerKg: 18000,
    quantityKg: 400,
    village: 'Qumqo’rg’on',
    district: 'Qumqo’rg’on',
    region: 'surkhandarya',
    harvestDate: harvest(7),
    phone: '+998902223344',
    telegramUsername: 'anor_surxon',
    isSoldOut: false,
    createdAt: daysAgo(6, 15),
    description: 'Shirin nav, yirik. Yashiklarda.',
    unitLabel: 'kg',
    views: 77,
    seller: {
      id: 'demo-s10',
      fullName: 'Ulug’bek Xolmatov',
      phone: '+998902223344',
      telegramUsername: 'anor_surxon',
      village: 'Qumqo’rg’on',
      district: 'Qumqo’rg’on',
      region: 'surkhandarya',
    },
  },
  {
    id: 'demo-11',
    productName: 'Sarimsoq',
    category: 'sabzavotlar',
    pricePerKg: 22000,
    quantityKg: 180,
    village: 'Kitob',
    district: 'Kitob',
    region: 'kashkadarya',
    harvestDate: harvest(25),
    phone: '+998939998877',
    isSoldOut: true,
    createdAt: daysAgo(8, 11),
    description: 'Quritilgan, o’ralgan. Hozircha tugagan.',
    unitLabel: 'kg',
    views: 55,
    seller: {
      id: 'demo-s11',
      fullName: 'Rustam Nazarov',
      phone: '+998939998877',
      village: 'Kitob',
      district: 'Kitob',
      region: 'kashkadarya',
    },
  },
  {
    id: 'demo-12',
    productName: 'Sut (sigir suti)',
    category: 'sut_mahsulotlari',
    pricePerKg: 7000,
    quantityKg: 100,
    village: 'Oqdaryo',
    district: 'Oqdaryo',
    region: 'samarkand',
    harvestDate: harvest(0),
    phone: '+998905556644',
    whatsappNumber: '+998905556644',
    isSoldOut: false,
    createdAt: daysAgo(9, 7),
    description: 'Har kuni ertalab va kechqurun sog’iladi.',
    unitLabel: 'litr',
    views: 29,
    seller: {
      id: 'demo-s12',
      fullName: 'Dilshod Ochilov',
      phone: '+998905556644',
      village: 'Oqdaryo',
      district: 'Oqdaryo',
      region: 'samarkand',
    },
  },
];

export function getMockListingById(id: string): Listing | undefined {
  return mockListings.find((l) => l.id === id);
}
